### ISSUE TITLE
Make masterpresentasjon v1 (Arbeidsflate)

### ISSUE THREAD

**Issue by krteige** [digdir/dialogporten-frontend#1056]

**Comment by MetteSaltnes** [comment]
Denne kan vi vell sette til done?

**Comment by MetteSaltnes** [comment]
V1 laget i figma og videreutvikles fortløpende:  https://www.figma.com/slides/i2nB7GHr8bAbxavheHREkV/Masterpres-Arbeidsflate-%2B-Dialogporten?node-id=1-312&t=UsT3SncWTKAqnKzp-0
