### ISSUE TITLE
Explore general UI improvements

### ISSUE THREAD

**Issue by vildestixrud** [digdir/dialogporten-frontend#110]
Explore general layout improvements. What can be simplified based on well-known ui-patterns and best practice?

```[tasklist]
### Layout
- [x] Header
- [ ] Footer
- [x] Navigation
```

```[tasklist]
### Feedback
- [x] Modals
- [x] Snackbar/Toast
```

```[tasklist]
### Context
- [x] Desktop
- [x] Mobile
```

**Comment by ingefossland** [comment]
![image](https://github.com/digdir/dialogporten-frontend/assets/1138656/6f7b865b-5057-4edd-ba86-26ab9dcec243)

Early sketches for modals + toast.

**Comment by ingefossland** [comment]
![image](https://github.com/digdir/dialogporten-frontend/assets/1138656/a55f76ff-deba-4b5e-a10c-bb82f4c9ccaf)

Early mobile sketches for modals + toast.

**Comment by indiamaydesign** [comment]
Closing the issue as we will explore footer functionality in #175. We have not created an epic for modals yet so this may need to be created later on.
