### ISSUE TITLE
Explore alternative solutions - part A

### ISSUE THREAD

**Issue by LisLonning** [digdir/dialogporten-frontend#12]
### **Beskrivelse**
Før vi lander på en løsning, utforske alternative løsninger - del A (minimumsløsning) for å forstå ulemper og fordeler med ulike løsningskonsept og hvilken løsning som best treffer behovene innsikten peker på.

Explored in:
#63 

Analysed the following to identify best practice patterns:
1. Gmail
2. Outlook 
3. Digipost
4. Spotify

**Comment by indiamaydesign** [comment]
@ingefossland just removing you from this one because Sigurd explained that people shouldn't be assigned to epics, but should be assigned to tasks :)
