### ISSUE TITLE
Suport legacy HTML and markdown on AdditionalInfo content

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1214]
**Introduction**

We only render AditionalInfo as text/plain today, but need to support HTML as legacy content and markdown as well.
Use embeddable HTML component for supporting this action.

**Implementation**

Section for (optional) additional info `InboxItemDetail` should render different depending on `mediaType`:

- `text/plain` : render as string (as if today)
- `text/markdown`: render using <Markdown /> component from workspace dependency `packages/embeddable-markdown-html/` 
- `text/html`: render using <HTML /> component from workspace dependency `packages/embeddable-markdown-html/` 

Highly consider extraction the section for additional in `InboxItemDetail` to a separate component, abstracting this logic.

**Testing**

Add examples in `mockDialogs` with both markdown and HTML.

**Comment by seanes** [comment]
cf. docs to validate issue

**Comment by LeifHelstad** [comment]
Test viser at:
**Ren tekst** vises, inkludert den rart formaterte .json-aktige teksten i meldingene fra skatt.

**Markdown** vises ok. F.eks. dette:
![image](https://github.com/user-attachments/assets/1d2e6fdb-a3a6-49e4-9e5c-491965061c72)

**HTML** finner jeg ikke eksempler på i TT02.
- Jeg bør ha en mulighet til å manipulere inn eller i dialoger på TT02
- Mulig noen på team Dialogporten kan hjelpe meg å finne data der AdditionalInfo inneholder html?

**Comment by LeifHelstad** [comment]
**HTML**
Dette:

![image](https://github.com/user-attachments/assets/55fc3c5a-77dd-4b6e-9ca8-6feb8d266f82)

gir:

![image](https://github.com/user-attachments/assets/ea49cb90-e6ab-4ab8-9e60-5be839f2bc88)
