### ISSUE TITLE
Bug: toggle global menu doesn't work

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1217]
![Image](https://github.com/user-attachments/assets/cf9eb2e3-46e2-41eb-94ed-6ed6c7628c40)

Closing global menu with close button does not work. 
Ensure that on select item also closes menu.

**Comment by LeifHelstad** [comment]
Finner ingen relevant pull-request for denne. Observerer at lukkeknapp "X" på menyen faktisk lukker menyen så setter uansett teststatus til passed.
