### ISSUE TITLE
Support legacy HTML as front channel embed in MainContentRef

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1221]
**Introduction**

In order to support HTML content migrated from Altinn 2 messages to Altinn 3, `<MainContentReference />` needs to be extended to support HTML. (Now only supporting markdown). 

**Implementation**

Refactor `MainContentReference` to render as `<Markdown>{data}</Markdown>` when `mediaType` is `application/vnd.dialogporten.frontchannelembed+json;type=markdown` and `<HTML>{data}</HTML>` when `mediaType` is `application/vnd.dialogporten.frontchannelembed+json;type=html`.

`getMainContentReference` should be refactored to use original `mediaType` for transparency, i.e. there is no need for custom type `markdown`.
 

Modify or add examples to `mockedDialogs` for testing purposes.

**Comment by LeifHelstad** [comment]
Eksempel fra Dev på dialog som inneholder MainContentReference.
Målet i Test er å gjenskape med html der.
<img width="292" alt="image" src="https://github.com/user-attachments/assets/0e0ad2bc-df15-4b22-bd6c-2411446ee337">

**Comment by LeifHelstad** [comment]
@seanes kan du dele testdata du benyttet her? Trodde jeg kunne sende inn HTML her, men det ser ut som den ønsker en URL.
Er det slik at den egentlig skal få en URL og så vise HTML-en bak den URL-en? 
![image](https://github.com/user-attachments/assets/6c3abf96-a620-4db2-ab9d-179eeb637b6a)

**Comment by LeifHelstad** [comment]
Har fått svar. Ja, det må være en URL, den må være https, men det er ikke nok. Den må være embedable slik som f.eks. denne:

https://dialogporten-serviceprovider-ahb4fkchhgceevej.norwayeast-01.azurewebsites.net/fce

<img width="388" alt="image" src="https://github.com/user-attachments/assets/0bc28481-be85-48b4-b25a-dbabbcc7a7d9">

Det gir OK testresultat for markdown, men jeg har foreløpig ingen god URL å embedde som skal rendres som html.

Hvis jeg via type sier at det leveres html i lenken som i realtiteten leverer markdown så blir resultatet dette:
<img width="447" alt="image" src="https://github.com/user-attachments/assets/297c085a-316c-4b28-a5ea-1e8e8f5ed575">

Altså fremkommer det ikke rundt innholdet at dette er html. Men så er jeg usikker på om det skal synes.

**Comment by LeifHelstad** [comment]
Herlig!
![image](https://github.com/user-attachments/assets/3d747ba2-5b01-4774-8aef-389eeb4d41d0)

På denne måten gir html identisk resultat fra same side som om man får med markdown.
![image](https://github.com/user-attachments/assets/3a246be6-b67a-40e5-a500-21a6703181d0)

Jeg vet ikke hvordan jeg i frontend kan avsløre om opprinnelig kilde var markdown eller html. Men siden jeg vet jeg har sent på begge måter og begge fungerer så er testen passert.

**Comment by seanes** [comment]
@LeifHelstad den ser på `mediaType` her for å vite om det er markdown eller html

**Comment by LeifHelstad** [comment]
Ser det i GUI via dev tools her. 
![image](https://github.com/user-attachments/assets/c72a4918-cb39-4b32-ae43-1c41ea4a5cac)
