### ISSUE TITLE
Improvements to "custom date range" picker

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1223]
It seems like the date field is not working as intended (broken?)

![Image](https://github.com/user-attachments/assets/aadca9a0-1401-4086-a922-80ad964aa29d)

- On click doesn't trigger a select date dialog like one would expect for input of type `date`.
- Focus does wrap around the entire input field (leaving the clear button unfocused)
- Clear button doesn't empty date (we should allow open ended or open started dates)
- There is missing padding between the "use date button" and the bottom of the dialog.

**Comment by seanes** [comment]
@mbacherycz is working on this.

**Comment by LeifHelstad** [comment]
Oppfatter endringen som en del av v1.6.1 der PR #1243 er en del av bygget.

Test av elementene i datovelger viser at rettelelsene er implementert OK. Setter derfor test passed på saken.

Observerer derimot at selve logikken rundt valg av dato er litt rar.
* Det logiske i et slik valg, der kalenderen sperrer deg på første og siste, vil være at intervallet er "fra og med til og med". Her oppleves det som kun "fra og til" med de valgte datoer ekskludert.
* Det virker som om status på meldingene kan være avgjørende for om de vises, selv om søket kun filterer på dato
* Alternativt så tenker jeg at filteret primært skulle gått på "opprettet", men at det kun går på "oppdaterte". Mulig begge skulle være tilgjengelig for bruker.

Lukker derfor denne issuen basert på at det grafikk-tekniske nå virker å være på plass. Oppretter en ny issue basert på observasjonene knyttet til det fuksjonelle.
