### ISSUE TITLE
Z-index issues with global menu bar

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1236]
![Image](https://github.com/user-attachments/assets/d5d6787b-7f1f-4eda-a49a-63c2eb9a8de5)

Menu should always be on top of other contextual menus, including sort order popover, cf. screenshot.

**Comment by LeifHelstad** [comment]
Test i TT02 viser at "Meny" nå legger seg fint foran både sortering og filter hvis en av dem er aktive samtidig med at meny åpnes.
Meny er alltid forrerst. Teststatus = Passed.
