### ISSUE TITLE
bug: Refreshing when partyId and search is stored in URL

### ISSUE THREAD

**Issue by alexdigdir** [digdir/dialogporten-frontend#1244]
Refreshing page breaks application when party and search is stored as query params.

**Comment by LeifHelstad** [comment]
Finner ikke helt PR for denne. PR #1201 virker relatert men har lavere løpenummer og kan være en tidligere rettelse som kan ha medført det som er ønsket løst her i #1244.

**Comment by LeifHelstad** [comment]
Her opplever jeg at "party" faller ut av url ved ulike handlinger. For eksempel om man 

- åpner en dialog
- henter frem lagrede søk 
- ...og ved andre manyvalg

Dette er en feil som også oppleves i randsonen av test av #1266 og som er blokkerende for test av #1298. Derfor opprettes en egen observasjon som går spesifikt på bortfall av "party" fra url, fremfor å beskrive alle følgefeil i detalj.

**Comment by LeifHelstad** [comment]
En sjekk på Tracking samtidig som det er relevant å vise avhengighet hos 1244 på 1317 for å kunne utføre test.
- [ ]
