### ISSUE TITLE
Feat: Saved search toggle button

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1256]
**background**

The save search button (`<SaveSearchButton />`) is currently just a naive button which saves the search and does reflect whether the search is saved or not.

![Image](https://github.com/user-attachments/assets/71d483c0-5204-4e64-873a-a83e86db26be)

**Definition of saved search**
A saved search is defined by search string (query) and filters from filter bar. At least one attribute needs to be set, i.e. if search string is empty AND list of filters is empty, the saved search button should not be visible.

**feature request / task**

Instead of being just a naive button, the button should be a button to toggle on (save) and off (remove the saved search) the search.

As a consequence the button has two states:

1. Search not saved
- Requires: There current search (cf. definition of saved search) is not found in the users repository of saved search for this view type and party.
- Appereance: `unfilled` ribbon (like today) along with label `Save search` (`Lagre søk`)
- onClick: clicking this should do the same as today, i.e. save the search

 1. Search already saved
- Requires: There current search (cf. definition of saved search) *is* found in the users repository of saved search for this view type and party.
- Appearance: `filled` ribbon along with label `Search saved` (`Søk lagret`)
- onClick: clicking this should (without prompting the user) delete the current search.

For both states, there should be a toast (using the snackbar) on either success or error, performing the mutation needed, triggered by the onClick, as today.

**Comment by LeifHelstad** [comment]
Fungerer:

- Det vises ikke knapp for søk hvis ikke et søk er definert
- Hvis et definert søk ikke er lagret fra før så vises "Lagre søk" med et blankt bånd.
-  Hvis man trykker "Lagre søk" med et blankt bånd så kommer en melding om at søket lagres.
- Hvis et definert søk er lagret fra før så vises "Lagre søk" med et fylt bånd.

![image](https://github.com/user-attachments/assets/199ae28b-263e-447a-85d0-c8833bfb0c86)


Observasjon:
- Hvis man trykker "Lagre søk" med et fylt bånd så kommer en melding om at søket lagres. Bruker ender da med et duplikat søk i listen over lagrede søk.

**Comment by LeifHelstad** [comment]
Observasjon 2: 

-  Hvis man kjører et lagret søk som privat bruker vil søker bli kjørt i kontekst av profesjonell bruker. Denne observasjonen er registrert som #1295
