### ISSUE TITLE
bug: Inbox counter should reflect unread items

### ISSUE THREAD

**Issue by alexdigdir** [digdir/dialogporten-frontend#1264]
Inbox counter notification should reflect number of _unread_ messages, not number of total messages as it is today.

![Image](https://github.com/user-attachments/assets/f4d37bac-9f35-4086-8b1b-ac191b0660cd)

**Comment by LeifHelstad** [comment]
@alexdigdir jeg mener å observere en bug her. 
Selv om begge meldingen er lest så vises det en rød ball med 2-tall frem til man gjør en "refresh" av siden.
Det mistenkes at dette er et chache problem. Men om det er i nettleseren eller lenger ned i stacken er ikke helt klart.

Eksempel fra TT02 v1.7.0. Dessverre var ikke fokus på de leste/uleste meldingene, men der er kun to meldinger og den øverste er tydelig allerede lest da overskriften ikke er i bold
![image](https://github.com/user-attachments/assets/e5706339-a11d-4e0a-a6e1-93a0b1cc4416)

Foreløpig konklusjon: Jeg forsøker å reprodusere feilen med leste meldinger og visning av uleste ved initiell åpning. Så opprettes en separat bug på dette.

**Comment by LeifHelstad** [comment]
To av fire er lest og tallet 2 vises i ballen, det er lovende.
19905895985 som bildet viser har perosnlig 2+2, så man kan sikkert diskutere hvor 2 tallet kommer fra.
Men 08895699684 har 1 lest og et utall uleste. Ballen viser 99 så det er en bekreftelse på at det er de uleste som telles. = Passed

![Image](https://github.com/user-attachments/assets/7c5813db-7676-4512-b26f-57d390aaf8a3)
