### ISSUE TITLE
bug: Refreshing page sometimes selects a different party

### ISSUE THREAD

**Issue by alexdigdir** [digdir/dialogporten-frontend#1266]
Steps to reproduce:

1. Log in as user 20905995783
2. Select "Sjelden Komfortabel Tiger AS"
3. Select "Søster Fantasifull"
4. Refresh page

Now  "Sjelden Komfortabel Tiger AS" is selected again, which is a bug.

![Image](https://github.com/user-attachments/assets/0e18abb8-6a68-4c56-8988-17d96c03a9aa)

**Comment by LeifHelstad** [comment]
Relater til både #1295 og #1298

**Comment by seanes** [comment]
Lukkes gjennom refererte issues.

**Comment by LeifHelstad** [comment]
Rettelsen er testet på v1.8.2 men kom trolig inn via v1.8.1 og pr #1310 

Isolert sett om man står i innboks og gjør refresh så vil man fortsette i rett innboks. Test passed.

Derimot, om man bytter fra privat til profesjonell og så valg av filter forsvinner party fra URL. Ved refresh er man da tilbake på privat. Ny observasjon opprettes for dette.
