### ISSUE TITLE
bug: Filters button not visible after performing search

### ISSUE THREAD

**Issue by alexdigdir** [digdir/dialogporten-frontend#1267]
Steps to reproduce:

Log in as any user
Type something in search field and press Enter

Filter button is not showing.

We want to give the user option to add filters even after performing a search, in order to improve search results further.

![Image](https://github.com/user-attachments/assets/6bf949e6-6dec-46be-80b8-4ae1ce0f9c4e)

**Comment by alexdigdir** [comment]
Turns out button is hidden when no filters are available for current items listed.
Maybe disable the button instead of hiding it?  A UI design decision.

**Comment by LeifHelstad** [comment]
@alexdigdir har du lukket denne uten videre kodeendring basert på eget spørsmål om det må til et nytt design valg om noe skal endres?

Det er ihvertfall fortsatt slik at hvis søket ikke gir treff har man heller ikke mulighet til å lagre søket om dette er rimelig eller urimelig skal jeg ikke mene noe om, kun konstatere. 

![image](https://github.com/user-attachments/assets/0d23f0fe-6589-4206-b69c-d3c908a5a4ff)

Men hvis søket gir treff og man trykker enter så viser grafikken at dette søket er lagret fra før. Det er det ikke. Blir nok logget en ny observasjon på det. 

![image](https://github.com/user-attachments/assets/026de9fe-d165-4fb9-bf9c-abfde3262cc9)

**Comment by LeifHelstad** [comment]
Lukker denne nå som passed basert på dette:
* Fritekst søk som gir treff men ikke er lagret fra før har mulighet for lagring
* Fritekst søk som gir treff og er lagret fra før har mulighet for sletting
* Fritekst søk som ikke gir treff gir ikke mulighet for hverken lagring eller sletting
