### ISSUE TITLE
Case: Samordnet registermelding

### ISSUE THREAD

**Issue by indiamaydesign** [digdir/dialogporten-frontend#127]
### Description

> Øke antall brukerreiser fra 0 - 2 -> BR (Samordnet registermelding) + SKD ? / NAV ?

#29 is the epic to be broken down here

### Additional Information

The need and immediate tasks are also covered in [the Dialogporten repo](https://github.com/digdir/dialogporten/issues/205) which outlines:

- That we will get more info on technical resources who will help the designers through at least 2 workshops to map out the journey in more detail
- Making the journey map easier to read, understand and share, through 3 scenarios that show what Dialogporten can be used for

### Update
Potentially turn this into an epic and have tasks under this

**Comment by AudunFK** [comment]
Under denne lenken ligger kartleggingen av samordnet registermelding: https://miro.com/app/board/uXjVKhGn_1c=/?share_link_id=335678357575
