### ISSUE TITLE
Bug: Unable to unsave a saved search

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1283]
**How to reproduce**

1. Login with 14886498226 at https://af.at.altinn.cloud/
2. Create a filter that already exists, e.g. add filter for avsender = "Fra Digitaliseringsdirektoratet".
3. Ensure button "Lagre søk" has filled ribbon indicating the search already is saved.
4. Click on "Lagre søk" (to unsave the search). Snackbar notifies about the save being removed, and then immediately notifies  that search has been saved.

**Expected**

1. It should be possible to unsave the search
2. Button with saved search should have a different label than "Save search".

**Necessary changes and other improvements** 

1. `SaveSearchButton` should only have one `onClick`, thus on `handleDeleteSearch` on `BookmarkFillIcon` should be removed and instead substitute `onClick` on `ProfileButton` instead.
---
2. Fragment around `ProfileButton` is not necessary and should be removed.
3. Change button label from "lagre søk" to "lagret søk" when the search is saved, cf. https://www.figma.com/design/yZLfugRSXOsdIXsZ7W5h43/Inbox-UI-%E2%80%93-del-A?node-id=165-47806&t=NbxsUW8om7iKum01-4 
4. `    if (typeof savedSearchId !== 'number') return;` check is redundant because of type in signature, remove this check.
5.  move `deepEqual` out of the component (e.g. to `deepEqual.ts` in same folder.

**Comment by LeifHelstad** [comment]
Selve "Slett" fungerer som beskrevet. "Lagre" fungerer også etter hensikten om man strengt holder seg innenfor der å Lagre å slette nydefinerte søk, og også å slette tidligere søk om det er identisk med et nydefinert som er kjørt.
Dette tilsier at  #1283 forsåvidt har teststatus Passed.

Jeg tar likevel med at det ikke går an å bruke lagrede søk ved en senere anldedning, da blir innboksene byttet rundt på som beskrevet i #1295
