### ISSUE TITLE
Prevent unwanted double click of gui actions

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1290]
Prevent the user from accidentally double clicking a gui action by disabling the button and showing a loader icon in the button (as a temporary solution) during the action round-trip.

ProfileButton supports `isLoading` already.

**Comment by LeifHelstad** [comment]
Starter test av denne nå. Den manglet Sprint og var gått under radaren. Finner i praksis ikke ut hvilke knapper det kan gjelde da det ikke oppleves GUI-actions med tilstrekkelig loadetid til at en loader-icon kan observeres,

**Comment by LeifHelstad** [comment]
Denne blir nok stående litt "Under test" da alle knapper jeg observerer er disablet.
Det er mulig å manipulere knappene til enabled via devtools ved å fjerne diabled fra dem. Men det skaper ikke noe mer "Action", knappene bare "fjærer". Jeg må avklare om det er implentert den nødvendige logikk i dialogporten før arbeidsflate granskes mer.

<img width="368" alt="image" src="https://github.com/user-attachments/assets/4bf116a7-3f08-4fb6-9d53-a89a6f168e4f">

**Comment by LeifHelstad** [comment]
Forsøkte å skape noe å vente på ved onclick:
onclick="(function(){
    alert('Skjer det noe med kappen?');
    return false;
})();return false;"

Men har fått forklart fra Mateusz at det er en "overrdden" onClick (med stor C i react) som er den funksjonen som gjør kallet til serveren bak kanppen og som også maniulerer knappen til å diables og vise "Loading". Samt å sette den tilbake.

Lukker foreløpig testen da Matheusz har demonstrert funksjonen ved at det i react er lagt inn en kunstig vent på 5 sek før respons fra server prosesseres.

I praksis krever manuell test (når server på et tidspunkt leverer enablede knapper) at serveren som kalles svarer tregt, eller at man manuelt setter på trottling i nettleseren via DevTools.
