### ISSUE TITLE
Its possible to do "Lagre Søk" on a serch marked with a filed ribbon. This will add a duplicate search to "Lagrede søk"

### ISSUE THREAD

**Issue by LeifHelstad** [digdir/dialogporten-frontend#1296]
Repro steps:

- Via "+ Legg til filter" legg inn et søk som allerede finnes i brukerens "Lagrede søk"
- Observer at båndet ved siden av "Lagre søk" er fyllt (en indikasjon på at søket er lagret fra før)
- Trykk lagre søk

Actual result:
- Det kommer en melding "Søk lagret"
- En duplikat variant av identisk samme søk dukker opp i listen "Lagrede søk"
![Image](https://github.com/user-attachments/assets/fb20d805-b07b-43eb-9f54-f5b512e3cadd)

Expected result:
- Hvis søket finnes fra før bør meldingen si at "Søket er lagret fra før"
- Deretter foretas det ingen oppdaterig eller lagring av gjeldende søk

**Comment by seanes** [comment]
Mulig dup, men kan du teste på ny @LeifHelstad ?

**Comment by LeifHelstad** [comment]
Issues #1256, #1293 og #1296 er varianter av samme fenomen og ble alle løst via PR #1270
