### ISSUE TITLE
Funksjonelle rariteter i datovelger for filter

### ISSUE THREAD

**Issue by LeifHelstad** [digdir/dialogporten-frontend#1307]
**ReporSteps:**
I miljø TT02 åpne person 19905895985
Gå inn på personens (Pære Altetende) dialoger
Legg merke til at det er 4 dilaloger

- "Søknad..." Avsluttet 15. januar 2024 15:24 (sett av bruker)
- "Melding..." Krever handling 25. desember 2023 12:34 (sett av bruker)
- Støtte..." Avsluttet 5. august 2023 00:00 (**ikke sett av bruker**)
- Støtte... "Under arbeid" 18. juli 2023 12:35 (**ikke sett av bruker**)

Trykk "+ Legg til filter" + "Oppdatert dato" + "Spesifiser dato"

Case 0
Tenk litt på det med "Oppdatert dato", inngår opprettet også i dette om det ikke er gjort oppdateringer?

Case 1
Sett "**Fra dato**" til 18, juli 23 (altså fra dato for første dialig)
Trykk "Bruk dato"

Case  2
Slett søket fra menyen og opprett et nytt
Sett "**Til dato**" til 18, juli 23 (altså fra dato for siste dialig)
Trykk "Bruk dato"

Case  3
Slett søket fra menyen og opprett et nytt
Sett "**Fradato**" til 18, juli 23 (altså fra dato for siste dialig)
Trykk "Bruk dato"

**Actual result:**
Case 0
I de påfølgende case utelukkes enkelte av dialogene selv om de er innenfor dato-range. Jeg mener at opprettet er "første oppdatert" så de også skal med. Ikke kun de som har fått oppdateringer etter opprettelse. (Det er mulig det er andre feilkilder som er årsak så alle Case her må sees under ett)

Case 1
Meldingen fra 18. juli er borte. Kan det være at søket er "fra", men burde være "fra og med"

Meldingen fra 5. august vises ikke. Det er ingen naturlig forklaring på at den ikke vises da filer kun er på dato.

Case 2
Filterets navn viser 18.juli 2023 - 15.januar 2024. Likevel vises ikke meldigene fra 18.juli og 5.august

Case 3
Ingen meldinger vises
Selve filterdialogen for valgt filter blir borte
Knappen "+ Legg til filter" blir borte
Man må klikke en gang innom "Utkast" eller "Sendt" og tilbake til "Innboks" for at der grafikske elementene skal komme tilbake i innboks

**Expected result:**

Case 1 & 2
Siden det er en begrensing i datovelger på at man ikke kan velge dato før dato på eldste melding så må valget av den datoen inkludere første melding.

Meldingen fra 5.august 2023 er innenfor dato-range og burde vises

Case 3
Det bør vises en "knapp" for valgt filter 15. okt - 15. okt (Altså for en dag)
Meldingen for denne ene dagen skal vises.

Obs!
I Case 3 kan det virke som om selve kallet til bakenforliggende feilet (litt som i #1306) da kan det være at problemet ligger i at det bakenforliggende kallet ikke takler en enkeltdag?

**Comment by seanes** [comment]
Forslag til endringer:

- Oppdatere filter for dato for dialog til å ta hensyn til `updatedAt` i stedet for `createdAt` (i `filters.ts`), samtidig som filterId bør endre navn til `updatedAt`
- Custom date range-picker bør ha default fra-dato (tidligste updated-dato) og til-dato (seneste updated-dato). 
- Velger man tomme til og fra, bør rangen være "alle datoer".

**Comment by LeifHelstad** [comment]
Den tekniske rettelsen av fra-til til å bli fraogmed-tilogmed er ok.
Meldinger innenfor intervallet blir heller ikke borte.
Basert på disse to er test passed.

En ekstra observasjon er om man setter date-range til et område mellom to meldinger slik at det er null treff. Da dannes ikke noe filter i menyen selv om listen er tom. Situasjonen blir litt odde for bruker som må klikke seg inn på andre menyvalg ev tur går visningen retter seg. Samme problem oppstår om man i søk-i-innboks skiver noe som ikke gir treff. Derfor opprettes en separat observasjon på dette med tomt resultatsett generelt.
