### ISSUE TITLE
Lagrede søk - plukker feil aktør dersom person er valgt

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1308]
### Description of the bug

Dersom man lagrer et søk på en person (som også har en organisasjon), f.eks. Søster Fantasifull (20905995783) i dev, og åpner søket, velges automatisk Sjelden komfortabel Tiger selv om søket er lagret for "Søster Fantasifull". 

https://af.at.altinn.cloud/?filters=%5B%7B%22id%22%3A%22sender%22%2C%22value%22%3A%22Oslo+kommune%22%7D%5D

Aktør bør bli uforandret.

- [ ] 

### Steps To Reproduce

1. Logg inn med 20905995783
2. Lagre et søk for Søster Fantasifull
3. Hent opp søket under lagrede søk

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/1356
```

**Comment by LeifHelstad** [comment]
Det motsatte har oppstått. Så sender lagrede søk på organsisasjon brukeren til person-visning.
Etter en mistanke om at gamle søk manglet party har jeg slettet alle på organisasjon og bygger dem på nytt.

Hjalp ikke lage søket for organisasjon på nytt. Oppretter en ny bug som jeg lenker til som task fra denne siden den feilen blokkerer videre test her.

**Comment by LeifHelstad** [comment]
Lagring og henting av lagrede søk for en aktør som er organsiasjon holdes nå som forventet på samme aktør. Test passed.
<img width="436" alt="image" src="https://github.com/user-attachments/assets/09d85cca-acb6-4355-980b-a5b2e7ceca36">
