### ISSUE TITLE
Flere handlinger medfører at "party" droppes i URL noe som skaper ulike følgefeil

### ISSUE THREAD

**Issue by LeifHelstad** [digdir/dialogporten-frontend#1314]
Repro steps:

Felles prep-steg
* Stå i privat innboks for en bruker
* Observer at url ikke inneholder "party" parameter
* Bytt til en profesjonell innboks for samme bruker
* Observer at url inneholder en "party" parameter

Case1:
* Åpne en dialog
* Trykk refresh i nettlseren

Case2:
* En av
a. * menyvalg "Utkast"
b. * menyvalg "Sendt"
c. * menyvalg "Lagrede søk" 
d. * menyvalg "Arkiv" 
e. * menyvalg "Papirkurv" 
+
* Trykk refresh i nettlseren

Actual result

Case1 og Case 2abcde:
* Parameter "party" forsvinner fra URL
* Grafikken tilsier at man er tilbake på privat visning, selv om noe av innholdet som vises er fra profesjonell innboks

Exprected result
* Parameter "party" skal ikke forsvinne fra URL
* En refresh i nettleser skal ikke medføre at bruker byttes til annen visning/context enn den for øyeblikket gjeldene

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/1356
- [ ] https://github.com/digdir/dialogporten-frontend/issues/1355
```

**Comment by LeifHelstad** [comment]
Issues #1298 og #1244 vil ansees som feilet i test frem til denne #1314 blir løst.

**Comment by seanes** [comment]
Bør sees i sammenheng med https://github.com/digdir/dialogporten-frontend/issues/1317

**Comment by LeifHelstad** [comment]
Rettelse av enkelte varianter som kastet bruker fra person til organisasjon har medført at andre varianter kaster bruker fra organisasjon til person. Videre test av denne er ikke anbefalt før #1356 er rettet.

**Comment by LeifHelstad** [comment]
Fortsatte testing på dette da #1356 ble løst. Det gjorde at man kunne åpne en dialog etter filtrering.

Opplever da det som er beskrevet i #1355 at ved åpning av dialog går party tapt.
-> Endrer fra "Under test" til "Failed" for legger til #1355 på "Tracking" lista.

**Comment by LeifHelstad** [comment]
Denne er på mange måter "Feature" til #1355 og #1356 som begge er løst i dag og verifisert i af.tt. Test passed.
