### ISSUE TITLE
Frontend becomes unresponsive after a while when loading dialogs with embeddable content

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1345]
Could be related to #1335 ? 

cf. https://digdir.slack.com/archives/C07JGSEN02W/p1730818614304199

Experienced with user  26818999827

**Comment by LeifHelstad** [comment]
Jeg opprettet aldri noen egen issue på dette, men jeg opplevde problemet og har forsøkt å gjenskape så godt som mulig det heg holdt på med 5. november. Nå oppleves ikke lenger heng. Test passed. 
![image](https://github.com/user-attachments/assets/0a3c65f1-5c71-4453-8d84-098dae79aa48)
