### ISSUE TITLE
fix: history back should read query correct selected party from state

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1346]
Selecting a party or all organization adds or modifies query params depending on option (`party` if organization or `allParties` if all organizations). Triggering history back, should respect previous query search param, i.e select correct party option depending on query param and fetch correct data (saved searches and dialogs) for this party/parties.

**Comment by LeifHelstad** [comment]
Denne fungerer ikke helt. Og testingen kompliseres av at #1347 ikke er levert. Jeg setter denne til Failed inntil videre

**Comment by LeifHelstad** [comment]
Denne fungerer nå. Det ble en enkel test med problemet i #1355 der man ved å åpne en melding mister party og havner i feil kontekst.
Denne #1346 retter problemet slik at en nettleser "history-back" sender bruker tilbake til forrige side der party fortsatt huskes rett.
Det var nødvendig å rette #1347 før #1346 kunne testes, hvis ikke var det for mye rart i history.
En observasjon fra #1347 var at nettleserloggen måtte slettes før testing kunne fortsette, hvis ikke ble den rare historikken husket og påvirket resultatet.
