### ISSUE TITLE
fix: browser history should not include double entries

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1347]
When performing a search, the url query parameter `search` gets added or modified with search query, e.g. `?search=hei`. Clicking history back / back button, should not render url with `search` param included, and input in search should be removed.

**Comment by LeifHelstad** [comment]
Det er noe caching i nettleseren som skaper litt usikkerhet i testen.
Noen ganger kommer søkekriteriet dobbelt i nettleseren. I en helt frisk sesjon observerer jeg at hvis jeg gjør et søk så vil pil tilbake gi en URL uten search.
(Hvis man underveis angir et tomt søk altså at search= blank så er dette et gyldig søk og huskes,)
