### ISSUE TITLE
Attachments should be opened in new window or browser

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1358]
Attachment links in a dialog should specify `target` to be `_blank`, opening the attachment link in a new window or tab, depending on the browser default / user settings.

The link is open and does not require a cookie.

**Comment by seanes** [comment]
Tar du en titt?

For å teste:

1. Logg inn med Altetende Pære, 19905895985 i tt
2. Velg en dialog [Søknad om plass til foodtruck](https://af.tt.altinn.no/inbox/01922e2b-16ce-71ee-9486-73dc3fb7ad27) 
3. Klikk på Vedtak om godkjent søknad.pdf]
4. Ny tab skal åpnes med url https://altinn.no/ (tidligere ble https://altinn.no/ åpnet i samme tab)

**Comment by LeifHelstad** [comment]
Mouseover på lenken viser https://altinn.no

Å klikke lenken åpner en ny tab med url https://info.altinn.no

Men endringen er ny tab og det er OK.
At det kommer på en "info" foran i URL kan likegodt være noe som skjer på den altinn-siden som åpnes og er da ikke en del av rettelsen.

**Comment by seanes** [comment]
@LeifHelstad Når du går inn på https://altinn.no/ så blir du videresendt til https://info.altinn.no/
