### ISSUE TITLE
Filters for messages should show correct amount of messages

### ISSUE THREAD

**Issue by mbacherycz** [digdir/dialogporten-frontend#1383]
### Description

After applying one filter, another filter still shows the amount of messages as if no other filters applied.
Better user experience would be to show how many messages will be shown if that filter applied considering other filters. 
<img width="1310" alt="Screenshot 2024-11-18 at 08 33 14" src="https://github.com/user-attachments/assets/a6aebcb5-7d43-4c44-bc90-370ce1403bb5">
<img width="1125" alt="Screenshot 2024-11-18 at 08 33 20" src="https://github.com/user-attachments/assets/61bb3098-476c-4567-858a-ec14bddec0ee">

**Comment by LeifHelstad** [comment]
**Test;**
_Søk + Filter_ = OK

<img width="330" alt="image" src="https://github.com/user-attachments/assets/7cc3e67f-4666-4c8d-b73b-effa4013a300">

_Kun et filter_ = OK

<img width="200" alt="image" src="https://github.com/user-attachments/assets/0eb78eec-5db0-4520-b1ac-0770a3da54ad">

_Filter + Filer_ = OK
<img width="249" alt="image" src="https://github.com/user-attachments/assets/0a8a84e3-9797-4f4e-b0a3-ca31f338bc41">

_Filter + Filter + DatoFiler_ = Failed
<img width="501" alt="image" src="https://github.com/user-attachments/assets/9bad8902-b629-41de-9778-28c2bae0569f">

Det samme skjer med _Filter + DatoFilter_.  
<img width="503" alt="image" src="https://github.com/user-attachments/assets/8c718217-1a37-4dd5-abda-1eefd74c8f1a">

@mbacherycz kan du sjekke i koden om Dato filter ikke tar hensyn til resultatet av de andre filterne?

**Comment by LeifHelstad** [comment]
Observasjonen er logget som #1494 

Så lenge 1494 er uløst holdes 1383 på teststatus failed.

**Comment by LeifHelstad** [comment]
**Test:**
Basert på siste dagers diskusjoner på hvordan dato som intervall skiller seg fra andre felter som "avsender" og "status" som filterkriterie er det tydelig at feil som går på dato skiller seg fra mer generelle feil.

Det generelle med telling av antall dialoger et filtervalg vil presentere er løst generelt sett.
Det er en utfordring knyttet til dette for datovelgeren. Men #1494 er kun en av flere utfordinger med datovelger.

Ny konklusjon er at #1383 løser problemet med telling av dialoger i filtervalg generelt og teststats er derfor passed.
