### ISSUE TITLE
Bug: Inbox counter not reflecting actual status

### ISSUE THREAD

**Issue by alexdigdir** [digdir/dialogporten-frontend#1398]
Om man har en ulest melding som kommer opp som 1 i den røde badgen, og man går inn på dialogen som er ulest, så blir dialogen markert som ulest, men badgen viser fortsatt 1.

**Comment by LeifHelstad** [comment]
Testet OK for "nedtelingen" av 2, 1 og 0 uleste.
Ved 0 uleste forsvinner den røde ballen umidelbart når siste uleste åpnes.
