### ISSUE TITLE
Fallback if dialog.org is not found in organization list

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1445]
`getOrganization` for mapping dialog and dialog details returns `undefined`  if `dialog.org` does not exsist in Alltinns organization registry (https://altinncdn.no/orgs/altinn-orgs.json).

![Image](https://github.com/user-attachments/assets/cdb36fd9-b6b0-4433-a2da-f5b87d63a2ed)

![Image](https://github.com/user-attachments/assets/e6b27dc3-b75f-4e11-a59f-577074d2bdc8)

`getOrganization`  should just makes sense to return name (`dialog.org`) without logoURL.

**Comment by LeifHelstad** [comment]
Test:
Oppsummering så langt
Testen skulle gjøres på en organsisasjon som ikke finnes i https://altinncdn.no/orgs/altinn-orgs.json (siden de har logo).
For å kunne opprette en dialog må man som en av forutsetningene finnes i ressursregisterethttps://[platform.tt02.altinn.no/resourceregistry/api/v1/resource/Search](https://platform.tt02.altinn.no/resourceregistry/api/v1/resource/Search)

Jeg vet ikke hvordan koblingen er mellom ressursregister og selve tjenesten for create dialog. Så for å teste med noen som er kjent og som jeg vet virker så har jeg benyttet samme innslag i ressursregister som skatt, som allerede har sendt meldinger.

![image](https://github.com/user-attachments/assets/ad5cbaef-5d32-4a1a-89b5-a2638043e214)

Det store spørsmålet er da om jeg via noen av "tulle innslagene" i ressursregister kan opprette dialoger. (Og får jeg til det må det være en sikkerhetsbrist?)

**Comment by LeifHelstad** [comment]
**Test:**
Ved å benytte andre "identifier" fra ressursregisteret gis det feilmelding om at ressursen ikke finnes i ressursregister.
Siden den er i fila men gir den feilmeldingen så må det være en av to feil:

- Enten sjekkes en annen instans av RR.
- Eller så er i beste fall feilmeldingen upresis og der er en annen kobling som ikke er satt mellom RR og tjenesten.

**Comment by LeifHelstad** [comment]
Ressursen jeg benyttet i ressursregisteret fungerer ikke fordi den blir filtrert ut. 
Dialogporten ser kun etter følgende resourceType når den gjør oppslag i RR:
- GenericAccessResource
- AltinnApp
- CorrespondenceService

OBS!
Jeg mener da at feilmeldingen bør si at ressursen basert på ressurstype ikke finnet i RR

**Comment by LeifHelstad** [comment]
**Test:**

Fant en kandidat på en ikke ekte enhet.
"identifier": "legacy-correspondence"
"organization": "313268969"

Med den kunne det dannes en dialog som kan vises i arbeidsflate
"01939721-b8dc-76b1-80be-5f0e3facaf38"

Spørsmålet er da for fallback løsning er at det dannes en avatar med forbokstaven til ServiceOwner vist.

![image](https://github.com/user-attachments/assets/2e64494d-45c9-4e43-b76e-0e0e54a61384)
