### ISSUE TITLE
Dialoger på sub-party blir nå ikke hentet hvis sub-party har samme navn som party

### ISSUE THREAD

**Issue by LeifHelstad** [digdir/dialogporten-frontend#1459]
Ved test av dialogporten #1226 ble det oppdaget at dialoger på sub-party ikke blir presentert i arbeidsflaten.
En forutsetning for observasjonen er at et sub-party har samme navn som overliggende party.
![Image](https://github.com/user-attachments/assets/eb15501c-fcf6-4d94-9289-d9f6c5ef0bf1)

I et slikt tilfelle vil party og sub-party slås sammen til et menyvalg.
![Image](https://github.com/user-attachments/assets/5b84c729-7763-4865-9583-003c428218e5)

Problemet her (i test) er at det på 313345475 er 4 dialoger og på 311412876 er 2 dialoger.

Går man inn på listevalget vises kun de 4 dialogene på hovedenhet. (Noe som også ble indikert av 4-tallet i manyvalget.)

Hadde ikke party og sub-party hatt samme navn så hadde de ikke blitt slått sammen.
**Så vi må se på tilfeller der party og sub-party har samme navn som særtilfeller?** Stemmer det @elsand 
Hvis ikke blir det vel rart at de danner separate valg som kan vise dialoger når de har ulike navn.

Tre forslag til løsning litt basert på tolkning av forutsetningene:

Alt. A
Hvis to ulike orgnummer er slått sammen til et party-valg fordi de har like navn så bør vi endre slik at dialoger hentes for alle orgnummer som ble slått inn i dette valget. (Dette er antakelig det enkleste og sikreste valget hvis vi ikke utfordrer selve premisset.)

Alt. B
Hvis det ikke skal kunne opprettes dialoger på sub-party som har samme navn som sin "parent" så burde API-et hindre at dialogen opprettes, for den vil aldri bli vist.

Alt. C
Vi gjør ingen endring, for det er GARANTERT at ingen noensinne kommer til å opprette en dialog på et sub-party som har samme navn som "parent".

Alt. D
Vi må gå tilbake å se på selve premisset om at party og sub-party med samme navn kan slåes sammen til et menyvalg.

**Comment by LeifHelstad** [comment]
**Tilleggsinfo:**
Har sub-party annet navn enn party vises begge.
(Som bekrefter at dagens AF behandler det som et særtilfelle om de har samme navn.) 
![image](https://github.com/user-attachments/assets/5372d155-891d-4bf5-a1a8-60a04d2133b9)

**Comment by elsand** [comment]
Det vil definitivt kunne opprettes dialoger på subparties med samme navn som parent. Meningen med at dette ble slått sammen i AF var for å forenkle for sluttbruker, som ikke nødvendigvis har noe forhold til denne differansen. Så A er er det vi skal ha her, altså at det må gjøres søk mot DP-APIet på begge orgnrene.

Jeg tror forøvrig det kan skape noe forvirring for de som _har_ et forhold til denne differansen (det er jo tross alt noe som har eksistert siden ER ble etablert i 1995), så designet bør på en eller annen måte gjøre det mulig å se hvilke orgnr som gjelder her. @ingefossland

**Comment by LeifHelstad** [comment]
Test:

Retest på samme bruker som i beskrevet repro-step viser nå 6 og ikke kun 4 meldinger. Den ene meldingen har et tydelig hint om at den er til sub enhet.
<img width="502" alt="image" src="https://github.com/user-attachments/assets/2f60a81a-13cb-49a3-ba5b-061e797cd267">

Skal gjøre en test til med 12907499179 som har 9 enheter, 4 hoved og 2 sub med eget navn og 3 sub med samme navn som sin hoved.
Ved å sette en melding på hver er det forventet at 6 enheter listes, 3 med en dialog og 3 med to dialoger.

**Comment by LeifHelstad** [comment]
**Testresultat:**

Pro:
Det virker stort sett som om meldinger hentes samlet fra party og sub-party der de har samme navn.

Con:
Valglisten for aktører denne personen har tilgang til viser ikke opptelling av antall meldinger per aktør (lenger).
Det kan lett mistenkes at dette er noe som kan trigges av det her telles for to?
Problemet gjelder ikke for aktører som kun har meldinger på seg selv eller på org topnivå og ingen sub....

![image](https://github.com/user-attachments/assets/5e721a03-a3b2-40ff-b1ca-27ad6431e82c)

@mbacherycz jeg skal se om jeg kan snevre inn problemet litt, men jeg tror du kan begynne å se på koden for "preview" av antall meldinger per aktør i valglisten for aktører om det kan oppstå et problem når det er treff på flere orgnr samtidig på samme navn.

**Comment by LeifHelstad** [comment]
Arbeidsflate vet tydeligvis at mer enn en aktør har dialog på seg, for ellers hadde ikke "Alle virksomheter" blitt vist.
Men velges "Alle virksomheter" så blir resultatsettet tomt.

**Comment by LeifHelstad** [comment]
@mbacherycz Tror jeg ser omtrent hvor pronblemet oppstår.

        {
            "party": "urn:altinn:organization:identifier-no:313549461",
            "name": "ORDENTLIG VIRTUELL TIGER AS",
            "partyType": "Organization",
            "isDeleted": false,
            "hasKeyRole": true,
            "isCurrentEndUser": false,
            "isMainAdministrator": true,
            "isAccessManager": true,
            "hasOnlyAccessToSubParties": false,
            "subParties": [
                {
                    "party": "urn:altinn:organization:identifier-no:311615696",
                    "name": "DYPSINDIG FUNKSJONELL FJELLREV",
                    "partyType": "Organization",
                    "isDeleted": false,
                    "hasKeyRole": true,
                    "isCurrentEndUser": false,
                    "isMainAdministrator": true,
                    "isAccessManager": true,
                    "hasOnlyAccessToSubParties": false
                },
                {
                    "party": "urn:altinn:organization:identifier-no:311615688",
                    "name": "UPRESIS KONSENTRISK FJELLREV",
                    "partyType": "Organization",
                    "isDeleted": false,
                    "hasKeyRole": true,
                    "isCurrentEndUser": false,
                    "isMainAdministrator": true,
                    "isAccessManager": true,
                    "hasOnlyAccessToSubParties": false
                }
            ]
        },

**Comment by LeifHelstad** [comment]
Observasjonen er logget som #1492 

Så lenge 1492 er uløst holdes 1459 på teststatus failed.

**Comment by LeifHelstad** [comment]
**Test av 1459 etter rettelse av 1492:**

Nå telles alle 9 dialoger på "Alle virksomheter".
Summen for de seks navngitte er også 9.

![image](https://github.com/user-attachments/assets/c808ded5-8853-46d9-8f4e-b183f419502e)

Tar inn notatene fra test 6.desember da de radene ble opprettet. Det er samsvar mellom hvilke som har like navn i party og sub-party og hvilke som er "slått sammen" eller ikke:

_Opprette for alle org 12907499179 har tilgang til
"urn:altinn:organization:identifier-no:213294342"
	"name": "LATTERMILD ORIENTAL TIGER AS"
	"01939be0-15e1-72ab-8261-2798d078b57c"
	"urn:altinn:organization:identifier-no:215421902"
		"name": "LATTERMILD ORIENTAL TIGER AS"
		"01939be0-a01f-71bb-8f01-9a3bbeaf3324"
"urn:altinn:organization:identifier-no:313549461"
	"name": "ORDENTLIG VIRTUELL TIGER AS"
	"01939be1-3fc5-775e-8b7f-7710b348d210"
	"urn:altinn:organization:identifier-no:311615696"
		"name": "DYPSINDIG FUNKSJONELL FJELLREV",
		"01939be1-abaa-70e7-9301-2c96e773145c"
	"urn:altinn:organization:identifier-no:311615688"
		"name": "UPRESIS KONSENTRISK FJELLREV"
		"01939be2-1b72-744e-a972-978f88f7829a"
"urn:altinn:organization:identifier-no:313776816"
	"name": "PLUTSELIG NYBAKT TIGER AS"
	"01939be2-817c-7426-9ad7-1d598c6caf16"
	"urn:altinn:organization:identifier-no:315073693"
		"name": "PLUTSELIG NYBAKT TIGER AS"
		"01939be3-131e-739d-ad97-119614c6d3c6"
"urn:altinn:organization:identifier-no:312409216"
	"name": "STYRBAR UTTRYKKSFULL TIGER AS"
	"01939be3-7990-73a5-9d74-2c73da20944d"
	"urn:altinn:organization:identifier-no:314518748"
		"name": "STYRBAR UTTRYKKSFULL TIGER AS"
		"01939be3-f112-75fe-a039-458acc1612bd"_
