### ISSUE TITLE
Telling av dialoger i meny feiler i sin helhet hvis en org bruker har tilgang til har flere sub-parties (med ulike navn?)

### ISSUE THREAD

**Issue by LeifHelstad** [digdir/dialogporten-frontend#1492]
**Repro steps:**
Observasjonen er gjort ved test av #1459 

Åpne arbeidsflate med n bruker som har tilgang til flere aktører og det finnes dialoger på flere av aktørene.

Et godt er eksempel fra af.tt er 12907499179 som har har 9 enheter, 4 hoved og 2 sub med eget navn og 3 sub med samme navn som sin hoved. Og der hver av disse 9 enheten har en dialog hver.

**Actual result:**
Preview av antall dialoger per aktør vises ikke.

![Image](https://github.com/user-attachments/assets/1d765199-ccc5-4929-84d7-4a326816e16b)

**Expected result:**
Et det på samme måte som for denne andre personen blir gjort en telling av dialoger per aktør som vises i menyen. ![Image](https://github.com/user-attachments/assets/61d7cdf0-5202-4f37-84e4-b4afeb82de74)

**Hypoteste på feilkilde:**
Tror jeg ser omtrent hvor pronblemet oppstår.
Her har sub-parties ulike navn sett opp mot party. Og det det også to sub-parties.

Jeg tror disse to kriteriene må oppfylles for at feilen skal oppstå:
* Party har mer enn et sub-party.
* Sub-party har annet navn enn party. (kan også være at det holder at flere sub-parties har ulike navn?)

Flere symptomer.
I arbeidsflate tar det lang tid når man åpner de to sub-parties som har egne navn. Så vises ingen dialoger, selv om det er forventet en på hver av dem. Jeg vil mistenke at det er dette som skaper trøbbel for "preview" tellingen i menyen også.

    {
        "party": "urn:altinn:organization:identifier-no:313549461",
        "name": "ORDENTLIG VIRTUELL TIGER AS",
        "partyType": "Organization",
        "isDeleted": false,
        "hasKeyRole": true,
        "isCurrentEndUser": false,
        "isMainAdministrator": true,
        "isAccessManager": true,
        "hasOnlyAccessToSubParties": false,
        "subParties": [
            {
                "party": "urn:altinn:organization:identifier-no:311615696",
                "name": "DYPSINDIG FUNKSJONELL FJELLREV",
                "partyType": "Organization",
                "isDeleted": false,
                "hasKeyRole": true,
                "isCurrentEndUser": false,
                "isMainAdministrator": true,
                "isAccessManager": true,
                "hasOnlyAccessToSubParties": false
            },
            {
                "party": "urn:altinn:organization:identifier-no:311615688",
                "name": "UPRESIS KONSENTRISK FJELLREV",
                "partyType": "Organization",
                "isDeleted": false,
                "hasKeyRole": true,
                "isCurrentEndUser": false,
                "isMainAdministrator": true,
                "isAccessManager": true,
                "hasOnlyAccessToSubParties": false
            }
        ]
    },

**Comment by seanes** [comment]
Feilen var at `undefined` ble sendt for suparties der subparties-listene var tomme, så kallet som beriker listen med badge count var tom (pga feil).

**Comment by LeifHelstad** [comment]
Test:
Nå teller den som forventet. (Og den gjør det i "ny" altinn-components drakt 👍 )

![image](https://github.com/user-attachments/assets/e9db7048-5c2b-41ef-9271-9f030acab302)
