### ISSUE TITLE
OnClick on AutoComplete scopes ("alt i innboks") should work as onEnter with the item is selected

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1498]
To reproduce:

1. Search for "skatt" with user 14886498226
2. Click on "<<skatt>> i innboks"
3. Nothing happens

![Image](https://github.com/user-attachments/assets/650fda6a-3bd9-4f71-ac29-c94ed8309fa8)

Expected behaviour:

Should show results for all items in inbox.

**Comment by LeifHelstad** [comment]
**Test:**

@seanes 
Indikatoren er litt misvisende da den sier "< > i innboks siden antallet som telles opp ikke er i innboksen alene:

![image](https://github.com/user-attachments/assets/5aadfefe-20dc-4588-b977-03f945ed1adb)

Med bruker 26818999827 så gir søk på "arbi" 9 treff. Men det er kun 8 av treffene som er i "innboks"

![image](https://github.com/user-attachments/assets/3a4fc643-a90c-4e2f-bde4-f4ad4f2e9841)

Det 9. treffet er i "papirkurv"

![image](https://github.com/user-attachments/assets/ce267d96-53a1-4558-9b32-5d6496a96a1f)

**Comment by LeifHelstad** [comment]
Oppretter separat issue på språkfeilen at "innboks+papirkurv+++" i søket kun heter "innboks".
