### ISSUE TITLE
Remove Header and GlobalMenuBar

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1499]
Remove components not in use, including tests, css and translations (only used by these components).

**Comment by LeifHelstad** [comment]
**Test:**
_Header_
Badge elementet i Header benytter fargesetting etter syntaks fra altinn-componets så Header må være erstattet med felles.
![image](https://github.com/user-attachments/assets/87ac99f5-2d2a-477e-8958-163fb40c9ad1)
![image](https://github.com/user-attachments/assets/47abac03-51d5-4cd6-8630-ff3f6da80ca3)

_GlobalMenu_
Samme indikator på at global meny er erstattet
![image](https://github.com/user-attachments/assets/79c8ce84-b460-454f-8ba1-4d1adbec7501)
