### ISSUE TITLE
Replace Badge component with component from altinn-components

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1500]
Remove copy in AF.

**Comment by LeifHelstad** [comment]
Test:

Gransker dette elementet som vises i dagens arbeidsfalte og er en "badge"
![image](https://github.com/user-attachments/assets/37298c01-0c31-4a5e-801b-d90c97b28d51)

I følge parametersettingen

> Badge has color prop, either subtle (this is the same as neutral) or alert (this is the same as strong)

Så følger den gledene syntaksen fra altinn compontet med "alert" fremfor den gamle lokale som benyttet "strong". 
![image](https://github.com/user-attachments/assets/0cbde82e-4904-4496-acc5-359f8015ac42)

Badge fra altinn componets benyttes i arbeidflate i dagens testmiljø. Teststatus = Passed.
