### ISSUE TITLE
Som bruker ønsker jeg at meldinger i innboksen åpner seg opp i en ny side når jeg klikker på den, for å lettere fokusere på innholdet i dialogen.

### ISSUE THREAD

**Issue by hansdragnes** [digdir/dialogporten-frontend#1520]

**Comment by hansdragnes** [comment]
**Levert**
Levert. Dialoger åpnes i en egen side med flere detaljer når bruker klikker på et element i list view.
**Kommentar til levert**
Instilling om man ønsker dette eller ikke? Spm om man ønsker å deaktivere funksjonen?

**Comment by LeifHelstad** [comment]
## Testkjøring
### Story:
_Som bruker ønsker jeg at meldinger i innboksen åpner seg opp i en ny side når jeg klikker på den, for å lettere fokusere på innholdet i dialogen._

### Tolkninger:
* _Meldinger i innboksen_ = vedlegg(?)
* _ny side_ = ny fane(?)
* _å lettere fokusere på innholdet i dialogen_ = at ikke dialogen endrer form og struktur

### Testdata
Lenken å trykke på
![image](https://github.com/user-attachments/assets/36e40fd9-594f-424b-9190-34c813cd21f1)


### Testresultat
Arbeidsflaten vises fortsatt i den gamle fanen og innholdet i dialogen er uendret
Vedlegger er åpnet i en ny fane.
![image](https://github.com/user-attachments/assets/51461508-2b04-433d-a509-f1b5ab56fe62)
