### ISSUE TITLE
Bug: Search should include dialogs for sub parties of selected party

### ISSUE THREAD

**Issue by mbacherycz** [digdir/dialogporten-frontend#1562]
### Description of the bug

Search bar should NOT filter out sub parties messages. 
As of now it is filtering out the sub party dialogs in both search popup and in the inbox. 
After fix, uncomment test scenario in flatPartySubParty.spec.ts

https://github.com/user-attachments/assets/f5346b7b-4093-4a62-a9d6-06cc9383e536

### Steps To Reproduce

Check recording

**Comment by LeifHelstad** [comment]
**Test:**

Aktørvalget "LATTERMILD ORIENTAL TIGER AS" er en sammenslåing av to org med samme navn der den ene er sub-party til den andre. Hver virksoomhet er bærer av en dialog hver.

Party
"urn:altinn:organization:identifier-no:213294342"
	"name": "LATTERMILD ORIENTAL TIGER AS"
	"01939be0-15e1-72ab-8261-2798d078b57c"

Sub-party_
	"urn:altinn:organization:identifier-no:215421902"
		"name": "LATTERMILD ORIENTAL TIGER AS"
		"01939be0-a01f-71bb-8f01-9a3bbeaf3324"

I menyen for aktørvalg (der de er slått sammen til et navn) telles det opp to meldinger.
I listen over dialoger vises begge meldingene.

Test Passed!

![image](https://github.com/user-attachments/assets/b33b8e16-4fef-46be-af53-00536f128b97)
