### ISSUE TITLE
Feat: Preserve Active Filters in URL

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1598]
**Feature Request: Preserve Active Filters in URL**

**Description:**
To maintain a consistent and user-friendly experience, active filters chosen by the end-user should be preserved in the URL. This ensures filters are persistent across page reloads or when bookmarks are saved. Additionally, sensitive data such as party IDs should not be included; instead, names or other non-sensitive identifiers should be used.

**Background:**
Currently, filters are being utilized as query parameters to rehydrate the filter state (e.g., populate search and filters with pre-selected values) when loading "saved searches." However, once these values are loaded, the filters query parameters are removed from the URL. This approach introduces unwanted side effects and is brittle to maintain.

Furthermore, the URL is not being updated when filters are applied. As a result, reloading the page or manually saving a bookmark does not preserve the active filters.

**Proposed Improvements:**

1. **Dynamic URL Update:**
   - Applying filters should dynamically update the URL to reflect the active filters.
   - This ensures that the current state is easily shareable and bookmarkable.

2. **Persistent Reloads:**
   - Reloading the page should load the filters from the URL and rehydrate the state seamlessly.

3. **Context-Aware Filters:**
   - Filters that are not applicable for the selected party should be ignored and removed from the URL.
   - Example: If a filter is applied to Party X but the user switches to Party Y, and the filter is not relevant to Party Y’s dialogs, it should not be retained in the active filters.

4. **Retain Query Parameters:**
   - After filters are loaded from the URL, the query parameters should remain intact.
   - This prevents unexpected behavior and ensures consistency for users navigating back or refreshing the page.

**Acceptance Criteria:**

- The URL should accurately reflect the active filters at all times.
- Reloading or bookmarking a page with active filters should maintain the filter state.
- Filters irrelevant to the current party should be excluded from the URL.
- Query parameters should not be removed after loading filters.
- Party IDs should be replaced with names or other non-sensitive identifiers in the URL, e.g. for senders and receivers. (This is already in place today).

**Technical Notes:**
- Ensure changes are compliant with security standards to avoid exposing sensitive information in the URL.

**Comment by LeifHelstad** [comment]
# TestRun
## TestData (1xx)
TD-100 + 101 + 102 + 104 : Aktør 08895699684 : Avsender : DMF
TD-103 : "CRTL + R"

## ActualResult (1xx)
🟢 AR-100 + 101 + 102 + 104 : https://af.tt.altinn.no/?loggedIn=true&sender=Direktoratet+for+mineralforvaltning
🟢 AR-103 : Sidne lastes på nytt. URL = OK, viste filtre = OK, listede dialoger = OK

**Comment by LeifHelstad** [comment]
## Observasjoner
Det er gjort en parallell observasjon underveis i testen. Denne oppretter Sean en egen sak på (som eventuelt kan refereres her senere).
Når man velger aktør "Alle virksomheter" får man i utgangspunktet denne URL
> https://af.tt.altinn.no/?allParties=true

Hvis man så velger en konkret aktør etterpå så fosvinner ikke allParties=true fra URL

> https://af.tt.altinn.no/?allParties=true&party=urn%253Aaltinn%253Aorganization%253Aidentifier-no%253A312560879

Bytter man til en tredje vil man bytte den spesifikk samtidig som man fortsatt drar rundt på allParties=True
Bytter man så til Alle Virksonheter så drar man også med seg den siste spesifikke videre

https://af.tt.altinn.no/?allParties=true&party=urn%253Aaltinn%253Aorganization%253Aidentifier-no%253A214012812
