### ISSUE TITLE
Share our work

### ISSUE THREAD

**Issue by indiamaydesign** [digdir/dialogporten-frontend#178]
### Oversikt

Epicen omhandler vår evne til å dele arbeidet vi gjør i team arbeidsflate. 

```[tasklist]
### My tasks
-  [ ] #141 
- [ ] #94 
- [ ] #127 
```

### Definition of done: 
Epicen vil være tett knyttet til OKRs i teamet. Den vil revurderes ved vært kvartal og måles i henhold til OKRs for Q1 2024 som satt i milestones. Lukkes så fort deling av arbeidet fora Arbeidsfase 1 ikke lengre er relevant.

**Comment by MetteSaltnes** [comment]
Skal denne lukkes eller arbeides den med?
