### ISSUE TITLE
Make Storybook deployable

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#190]
We want to share our custom components displayed as stories in Storybook via URL.

Deploy to Github pages together with Docusauros (common landing pages in between).

Relates to #211

**Comment by TheKnarf** [comment]
Dependet on #180

**Comment by TheKnarf** [comment]
> We want to share our custom components displayed as stories in Storybook via URL.
> Use Vercel or something similar for fast and non-configurable deployment? Or Azure?

I assume that we deploy it as a Docker container on Azure as with the rest of our setup.
