### ISSUE TITLE
Snackbar/toast

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#226]
## Concept
- Users should be notified with a toast/snackbar when performing micro interactions.

## When to use this pattern?
- Changing read/unread status
- Moving stuff between inbox and archive/trash

## Figma
https://www.figma.com/file/S4RwqVs8N0PzeotMTeXIwe/Innboks-UI?type=design&node-id=1241-39883&mode=dev

## UI sketches
![Image](https://github.com/digdir/dialogporten-frontend/assets/1138656/65e38af0-fd4e-4cd7-be19-28d922d337a7)

**Comment by LeifHelstad** [comment]
## Test
Funkjonen er fjernet ved et uhell og kan ikke testes før den er re-implementert via https://github.com/Altinn/dialogporten-frontend/issues/1653

**Comment by LeifHelstad** [comment]
## Test

### TC-100 - Lagring og sletting av søk

🟢 Snackbar vises igjen i GUI ved lagring og sletting av søk


![Image](https://github.com/user-attachments/assets/9e1dcaf6-a36a-4349-9a96-ceb51bb539a5)


### TC-200 - Flyttinger mellom innboks, arkiv og papirkurv

🟢 Snackbar vises igjen i GUI ved flyttinger mellom innboks, arkiv og papirkurv

<img width="456" alt="Image" src="https://github.com/user-attachments/assets/83d903c8-e423-42bb-b60d-311327a05a50" />


### Generell observasjon

🟡 det er ikke gradert farge over tid slik det er vist i bildet i "UI sketches"
> Er det at fargen på snackbar ikke graders over tid et problem @ingefossland
