### ISSUE TITLE
Local navigation concept (sidebar)

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#324]
## Concept
- Sidebar is built upon todays logic, with some small changes.
- Inbox should only display incoming dialogs.
- Ongoing dialogs or dialogs created by the user should be moved out of the inbox, possibly to a "draft" folder.
- Completed dialogs should not be automatically archived, but moved to a "sent" folder.
- Archive and deleted folders are continued as is.
- Saved searches are collected under a single menu item.
- Number of items per folder is displayed as a badge (for inbox, number of unread items).
- Links to other related parts of Altinn might be included as shortcuts.

## Questions
- Do people understand the difference between inbox, draft and sent?
- How do users organise their inboxes?

## Sketches

![image](https://github.com/digdir/dialogporten-frontend/assets/1138656/fcbe364f-5428-48d3-963e-c41f75123a64)

https://www.figma.com/file/S4RwqVs8N0PzeotMTeXIwe/Innboks-UI?type=design&node-id=1039-113306&mode=dev

**Comment by LeifHelstad** [comment]
## Test
Det er litt uklart hva som menes med disse begrepene. Det må avklares før test kan påbegynnes:
* incoming dialogs
* Completed dialogs

**Comment by LeifHelstad** [comment]
## Testobservasjoner rundt punktlisten Concept

🔵  Sidebar is built upon todays logic, with some small changes.
  - ikke verifiserbar da "todays logic" ikke er nærmere beskrevet

🟢 Inbox should only display incoming dialogs.
  - stort sett bekreftet. Men det er ikke gjort stort av test for å beviser negative tilfeller. Må testes nærmere etter implementering av #1517 

🟢 Ongoing dialogs or dialogs created by the user should be moved out of the inbox, possibly to a "draft" folder.
  - I det minste følger "Draft" dialoger prinsippet her. Det er godt nok frem til implementeringen av #1517 

🔴 Completed dialogs should not be automatically archived, but moved to a "sent" folder.
  - Eksempel fra Staging miljø viser at "Completed" forblir i "Innboks" (se detaljer i #53 og #1517)
  - Kan "Completed" bety mer enn en ting?

🔵 Archive and deleted folders are continued as is.
  - ikke verifiserbart uten nærmere beskrivelse av "as is". Sannsynligvis ivaretatt etter forventning.

🟢 Saved searches are collected under a single menu item.
  - "Lagrede søk" er et eget menyelement. Innholdet bak "Lagrede søk" følger hviklen aktør bruker har valgt.

🟡 Number of items per folder is displayed as a badge (for inbox, number of unread items).
  - 🟢 At antall elementer telles er implementert for alle bokser
  - At antall "unread" telles for innboks er endret siden denne saken ble spesifisert
  - 🟢 Nå viser innboks totalt antall elementer, så samme måte som alle de andre menyelementene, inkludert "Lagrede søk"
  - 🟢 Hvis noen blant totalen i innboks er ulest kommer det på en rød dott på ikonet for innboks.

🔵 Links to other related parts of Altinn might be included as shortcuts.
  - uklart hva dette betyr. Det er ingen kjente lenker i venstremenyen (sidebar) for arbeidsflate akkurat nå. 

## Testrapport

Konseptuelt er sidebar (venstremeny) implementert som beskrevet. Det er kommet til korreksjoner i løsningen som ikke samsvarer helt med beskrivelsen her i dette issuet, de lar vi passere i test.
I tillegg er det noen status- og lese-kombinasjoner som ikke er definert helt klart. De går ikke på selve menyen men hvilke list-views (som ligger bak none av menyvalgene) de enkelte dialoger sorterer under. Dette følges videre opp i #1517
