### ISSUE TITLE
Users should be notified when performing micro interactions

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#376]
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/226
```

**Comment by LeifHelstad** [comment]
## Test
Det hadde vært fordelaktig for test med en enkel liste over de "micro interactions" som er forventet å trigge denne typen notifications.

**Comment by LeifHelstad** [comment]
## Test

Generelt sett blir ""Users ... notified when performing micro interactions"

Dette er tester i #226 med eksempler fra GUI.

Det eneste er at det i #226 er gitt en "UI sketch" der snackbar elementene over tid endrer farge og fader ut. Slik fungerer det ikke nå. Så blir de stående en gitt tid med samme farge før de plutselig fjernes.

Dette følges opp via #226 så #376 lukkes som passed på (generelt) grunnlag av at brukere får et varsel.
