### ISSUE TITLE
Dialogs should include information on how to get in touch with the sender

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#377]
## Issues

- Many users will contact Altinn if they don't understand the content of a dialog.

## Hypothesis

- To assist users that need help, every dialog should include information on how to get in touch with the sender
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/297
```

**Comment by LeifHelstad** [comment]
## Test
Her er det mulig det må logges en bug, for påtvungen kontaktinformasjon er å finne i dagens dialoger i test.

**Comment by LeifHelstad** [comment]
## Test 2
Nå er #297 gått til design statusen "Research". Alle avvike nevnt i #377 håndteres videre i #297.

Lukker #377 da den er i praksis er et duplikat. Men, jeg gjør ingen re-åpne + re-lukke for å endre lukke-type.
