### ISSUE TITLE
Dialog concept, version 1

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#378]
## Concept
- Dialogs represent a letter or a task that should be clear and obvious to the user.
- Dialogs are built up of different elements, representing different content types.
- A dialog must have a title, sender/recipient and a body.
- Dialogs should include information on how to get in touch with the sender.
- Dialogs might include a list of attachments.
- Dialogs that represent a task should link to the task using distinct call-to-actions
- Dialogs that is part of a process might include a history/activity log of previous communication.
- Concept can be expanded with new elements, for example threaded dialogs, inline forms, payment information, etc. 

![Image](https://github.com/digdir/dialogporten-frontend/assets/1138656/20cd320c-fd09-4301-bcd3-43558be98e3f)

## Sender and recipient
- Sender is emphasised using bold and the senders logo.
- On dialogs in draft mode the order of sender and recipient should be reversed, indicating that the dialog is sent by a person or company.

## Dialog body
- Important content should not be hidden as attachments.
- Ideally dialog body should contain all information needed to understand the dialog.
- On dialogs with call to action, dialog body should explain the desired action.

## Attachments
- Use attachments for additional content, not full letters.
- Use documents labels that make sense to users, not "Document.pdf".

## Call to action
- Call to actions represent primary and secondary tasks expected to be performed by users.
- Use active labels that communicates intent

## Navigation
- When opening a dialog from a list view, users can navigate to next and previous dialog using the navigation bar on top

```[tasklist]
### Dialog elements
- [x] Dialog navigation (Back, Next, Previous)
- [x] Dialog title
- [x] Sender and recipient
- [x] Dialog body
- [x] Attachments
- [x] Call-to-action
- [ ] https://github.com/digdir/dialogporten-frontend/issues/297
- [x] https://github.com/digdir/dialogporten-frontend/issues/410
- [x] https://github.com/digdir/dialogporten-frontend/issues/411
- [x] https://github.com/digdir/dialogporten-frontend/issues/412
- [ ] https://github.com/digdir/dialogporten-frontend/issues/296
- [x] https://github.com/digdir/dialogporten-frontend/issues/413
- [ ] https://github.com/digdir/dialogporten-frontend/issues/298
- [ ] https://github.com/digdir/dialogporten-frontend/issues/139
```

**Comment by LeifHelstad** [comment]
## Test

De fleste elementet nevnt under "Concept" i første kommetar virker å være på plass.

Det er et unntak:
> 🔴  _Dialogs should include information on how to get in touch with the sender._

For øvrig finnes resten av de nevnte elementene.

![Image](https://github.com/user-attachments/assets/7979f9cb-7166-493f-bba9-2699f4f59fb5)

**Comment by LeifHelstad** [comment]
## Test 2
Etter gjennomgang på Refinement for Arbeidsflate ble det besluttet at alt åpent rundt kontaktinformasjon til avsender flettet inn i dialogen skal følges opp videre via #297.

Siden det eneste her i #378 som er merket med avvik er akkurat "kontaktinformasjon til avsender flettet inn i dialogen" så kan #378 lukkes med Teststatus = Passed siden det resterende følges opp via #297.
