### ISSUE TITLE
Dialog list item concept, version 1

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#379]
## Concept:
- Difference between letters and tasks can be indicated using content, status labels and metadata
- Type icons (message, form) does not add enough value. Users should understand what to do based on content.
- Indicating when and by whom a dialog have been updated will help people understand what is going on.
- Opening a dialog on a separate page is a better pattern than expanding it inline, making it easier to focus on a single task.
- Introducing bulk actions will help users organise their inboxes.

## UI sketches
![Image](https://github.com/digdir/dialogporten-frontend/assets/1138656/ed12ae78-97db-475b-9555-2c645743af83)

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/411
- [ ] https://github.com/digdir/dialogporten-frontend/issues/296
```

**Comment by LeifHelstad** [comment]
## Test
Konseptuelt virker alle elementene i liste-varianten av en dialog å være på plass

### Mottatte

![Image](https://github.com/user-attachments/assets/16f2c42b-13f4-405c-aebc-3bbab684a845)

### Utkast

![Image](https://github.com/user-attachments/assets/ab10fb22-eb18-4b41-a77c-fbbd4de3f7cf)
