### ISSUE TITLE
Case: Sykemelding

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#419]
```[tasklist]
### Tasks
- [x] Map out user journey to discover user needs and pain points
```

Kartlegging av sykemeldinger med painpoints: https://miro.com/app/board/uXjVKhGn_1c=/?share_link_id=335678357575

**Comment by AudunFK** [comment]
Under denne lenken ligger kartleggingen av sykemeldinger: https://miro.com/app/board/uXjVKhGn_1c=/?share_link_id=335678357575
