### ISSUE TITLE
Visning av å lagre søk

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#427]
CTA for å lagre gjeldende søk:

- Bør ikke være mulig å lagre duplikate søk
- Man må oppgi et navn for søket (prompt?)
- Ikon i CTA-knapp bør reflektere om søket allerede er lagret eller nytt (ved fyll)

**Comment by LeifHelstad** [comment]
Det er innført et banner som viser om søker et lagret fra før eller om man kan lagre det.
Er det lagret kan man benytte banner-ikonet til å slette det.

Denne saken har stått som Done siden mail. Men den er fortsatt Open og ikke Closed og fremkommer derfor i all raportering. Jeg setter den til Closed nå sammen med at denne kommentaren legges inn.

**Comment by LeifHelstad** [comment]
## Test

✅ Bør ikke være mulig å lagre duplikate søk
❔ Man må oppgi et navn for søket (prompt?)
✅ Ikon i CTA-knapp bør reflektere om søket allerede er lagret eller nytt (ved fyll)

Ignorerer den om at bruker må sette navn på søk. Det er mest brukervennlig slik det er nå med at bruker kan markere med et banner om søket er ønsket lagret. Dette gir også at bruker ser at søket et lagret fra før da banner allerede er satt. Det hinder også dobbel lagring av samme søk. For et gitt søk kan kun lagring toggles av og på. Man kan ikke dobbelt-lagre.

Navn på søket kan bruker angi ved en senere anledning.
