### ISSUE TITLE
Labels and priority in sidebar might be unclear and should be investigated further.

### ISSUE THREAD

**Issue by krteige** [digdir/dialogporten-frontend#476]
## Issues

- Inbox, drafts and sent ("Innboks", "Utkast, "Sent") is for the most part clear to users.
- "Nytt skjema" label isn't obvious. 
- The purpose of archive isn't obvious to everybody. 
- Trash should probably be labelled "Papirkurv" to make it clearer that things aren't erased forever.
- Saved searches ("Lagrede søk") is obvious, but might be more prominent?
- Explore placement, weighting in the menu items. Possible archive, deleted and saved searches must be given the same location
- We need to look at the wording of menu items on the left side

**Comment by LeifHelstad** [comment]
## Test

De felter som er nevnt fremkommer slik de er beskrevet som ønsket under overskriften "Issues" i første kommentar.
Det eneste som ikke kan bekrftes er "Nytt skjema", men det mistenker jeg er et valg som er blitt fjernet etter at saken ble opprettet.

![Image](https://github.com/user-attachments/assets/4f37ae80-3a16-4845-9e63-8dad24e9759e)
