### ISSUE TITLE
Users understand the basics of dialogs, but we need to look into more real use cases to identify patterns for history/activity, status and progress.

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#480]
## Findings
- Users understand the basic building blocks that make up a dialog.
- Users understand that the history represents a thread of previous events attached to the main dialog.
- Users understand which parts comes from the sender and which parts have been created by the user.

## Issues
- The copy on each element needs to be obvious, indicating clearly what has happened.
- We need to map out more real use cases to identify what kind og activity needs to be presented to the user.
- We need to map out real processes to identify how and what to present regarding dialog/activity status and progress.

## Hypothesis
- The main dialog should include a summary of everything the user needs to know and do.
- The activity log (history) should provide details of what has happened, when it happened and who made it happen.
- If an activity includes a piece of content, for example an attachment, that content needs to be made available to the user.
- If an activity includes a standalone dialog, user needs to be able to find the original dialog.

## Notes
- Check with legal what information needs to be present.
- We need to talk with users and stakeholders to identify pain points and needs.
- We need to map out the full journey, including stuff that does not hit the inbox.
- We need to map out all contact points, for example sms, email, offline communication, etc.
```[tasklist]
### Sprint 1
- [ ] https://github.com/digdir/dialogporten-frontend/issues/545
- [ ] https://github.com/digdir/dialogporten-frontend/issues/546
```

**Comment by LeifHelstad** [comment]
## Test
Dette oppfatter jeg mer som en "design-task" enn noe som er levert og kan testes. Teststatus=NA.
