### ISSUE TITLE
Update bulk-select in Inbox to match the new design

### ISSUE THREAD

**Issue by TheKnarf** [digdir/dialogporten-frontend#542]
### Description

Update the functionallity for selecting multiple items in the Inbox according to the new design

### Additional Information

Utforske hva som blir mulig å levere på til del A

### Delmål

- [x] Nytt design hvor det er en header og footer seksjon
- [x] Animasjoner når en åpner ActionPanel
- [x] Mobil
- [x] Skjule sidemenyen når multiselect er åpen
- [x] Når i bulkmodus så skal selecting virke anderledes (se figma)

**Comment by TheKnarf** [comment]
https://www.figma.com/design/yZLfugRSXOsdIXsZ7W5h43/Inbox-Sitemap?node-id=26-13051&t=w8EBEEa2YQa4RQBJ-0

**Comment by LeifHelstad** [comment]
Denne endringen er ikke (lenger?) synlig i staging af.tt og kan derfor ikke verifiseres der.

Funksjonen er derimot demonstrert i komponentbiblioteket her:
https://altinn.github.io/altinn-components/?path=/story/demo-inbox-inbox--bulk-mode

Siden issuet i utgangspunktet er satt til Done 12.juni uten å bli flippet fra Open til Closed så Closer jeg den nå.
