### ISSUE TITLE
User involvement / workshops - part 1

### ISSUE THREAD

**Issue by LisLonning** [digdir/dialogporten-frontend#6]
## Description
Based on the research gap identified from [mapping previously conducted research](https://github.com/digdir/dialogporten-frontend-react/issues/5), plan and execute user involvement to ensure that the solution(s) are built with humans at their core. 

Please attach / link to the relevant [research plan](https://github.com/digdir/dialogporten-frontend-react/issues/44).

## In scope
What's in scope for this analysis?

## Out of scope
What's out of scope for this analysis?

## Additional information
Links to relevant resources, documentation of other issues, UX sketches, technical architecture/requirements.

## Analysis
A description of how the analysis was done, what alternatives were considered etc

## Conclusion
What have we found out by doing this analysis

**Comment by indiamaydesign** [comment]
Didn't do a round of workshops as prioritised interviews and concept testing instead

**Comment by indiamaydesign** [comment]
Didn't do a round of workshops as prioritised interviews and concept testing instead
