### ISSUE TITLE
Antall uleste melder i inboks-elementet i sidebar bør være dynamisk

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#625]
P.t. hardkodet til 3, bør reflektere antall uleste meldinger som i brukerens innboks. Gjelder det for alle parties, eller kun for valgt filter? Må utforskes.

![Image](https://github.com/digdir/dialogporten-frontend/assets/3768832/d6e7e63f-e17b-40fe-bbd5-aafaf3b5d77f)

gjelder for alle "views".

**Comment by alexdigdir** [comment]
Denne har jeg fikset i en annen task...?
