### ISSUE TITLE
Prepare content for usability test

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#629]
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/638
```

**Comment by theresaharmanen** [comment]
@ingefossland vi har flyttet denne issue:n til *done* men kan vi også sjekke av tasken/issuen i listen som er lenket (638)? :)

**Comment by AudunFK** [comment]
Issue 383 er lukket - derfor lukker jeg også denne.
