### ISSUE TITLE
Visning for "ingen lagrede søk"

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#756]
Dersom bruker ikke har lagrede søk ser det p.t litt tomt ut:

![Image](https://github.com/digdir/dialogporten-frontend/assets/3768832/54b289e7-00f6-482a-b7c9-b02e07ee8fe8)

Det fremgår ikke av skissene hvordan dette skal vises.

Se https://www.figma.com/design/yZLfugRSXOsdIXsZ7W5h43?node-id=115-352050&m=dev#853334790 for diskusjon.

**Comment by TheKnarf** [comment]
Skissen fantes kun for mobil (men skal nok være lik på desktop):

![Image](https://github.com/digdir/dialogporten-frontend/assets/213777/7f562fdb-294f-42a5-a52a-35001a03f34c)

**Comment by seanes** [comment]
Skisse: https://www.figma.com/file/yZLfugRSXOsdIXsZ7W5h43?node-id=115%3A352050&type=design&fuid=1334880084753170792#853334790
