### ISSUE TITLE
Inbox: GUI actions

### ISSUE THREAD

**Issue by alexdigdir** [digdir/dialogporten-frontend#778]
Render action buttons received from Dialogporten API.

- Verifisere at nåværende implementasjon fungerer
- Hver knapp er i dag sin egen form
- Token må sendes med, dette ligger på dialogen (prop verdi dialogToken)
- Knappen skal være (er allerede?) disabled hvis isAuthorized er false, men vi må få inn informasjon til brukeren om hvorfor knappen er disablet. (Kommentar er lagt inn i Figma, venter på tilbakemelding fra design)
- DELETE støttes ikke av FORMS, enten må vi skrive om til å ikke bruke forms eller egen logikk kun for DELETE.
- Det er en egen prop som heter isDeleteAction
- GUI action er en egen storybook story

https://www.figma.com/design/yZLfugRSXOsdIXsZ7W5h43/Inbox-UI-%E2%80%93-del-A?m=dev&node-id=117-361338

**Comment by seanes** [comment]
Avsluttes - resterende oppgaver:

- https://github.com/digdir/dialogporten-frontend/issues/897
- https://github.com/digdir/dialogporten-frontend/issues/896
- https://github.com/digdir/dialogporten-frontend/issues/901
