### ISSUE TITLE
Lagrede søk: Confirm boks for sletting av lagrede søk

### ISSUE THREAD

**Issue by alexdigdir** [digdir/dialogporten-frontend#779]
Trenger input fra design

**Comment by alexdigdir** [comment]
Her trenger vi Figma-skisser fra Design

**Comment by seanes** [comment]
Bør samme dialog brukes for `prompt` i GUI actions?

**Comment by ingefossland** [comment]
Foreslår at vi bruker modalen fra designsystemet med dette forslaget til innhold:

![Image](https://github.com/user-attachments/assets/fc009b0a-9462-4c94-b8eb-3754e33e0b76)

1. "Ja, fortsett" utfører sletting
2. "Avbryt" lukker dialogen.
3. Checkboksen med "Ikke vis denne dialogen neste gang" fjerner modalen hvis brukeren vil slette en ting til. 
4. Selve slettingen bekreftes med en snackbar: "Søket ble slettet".

Valget om å bypasse modalen må kanskje kunne slås på igjen? Evt. kan det vare ut sesjonen, e.l. 

Samme modell kan brukes på flytting til arkiv og papirkurv:

![Image](https://github.com/user-attachments/assets/a1936bdb-3f16-4615-908b-63fe379f03af)

![Image](https://github.com/user-attachments/assets/26d742ad-ed5f-4975-8ba6-c5156643d92c)

Foreløpige skisser:

https://www.figma.com/design/yZLfugRSXOsdIXsZ7W5h43/Inbox-UI-%E2%80%93-del-A?node-id=1567-21040&t=PD0zLBZQ6tlEBdK9-1
