### ISSUE TITLE
Alerts should be personal.

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#84]
### Assumption

Users need to be able to select which alerts to receive and where to receive them. People need to be in control of their own contact information and alerts. Companies should not set up alerts on behalf of people. 

### Background

Users receive alerts from companies they no longer work at, or alerts for stuff they don't have access to, leading to confusion and frustration. Contacting customer service does not help. To remove an unwanted alert, a user need to contact a company admin and ask them to remove their email or phone number from company alerts. (Medlytt 17. oct 2023)

![Image](https://github.com/digdir/dialogporten-frontend/assets/1138656/bfc53399-4759-4dda-8e7f-8d287d1d9877)

(This screen allows companies to add alerts for any email or phone.)

### How to solve?

To avoid alerts for stuff a user cannot access, alerts from companies should be attached to access management. Fine tuning which alerts to receive and how to receive them should be controlled by the individual user.

**Comment by indiamaydesign** [comment]
Related to alerts specifically: "Vi er i gang med å utvikle et nytt [varslingsprodukt](https://github.com/Altinn/altinn-notifications) som skal understøtte mail/sms og visning av varsel i ulike portaler/arbeidsflater/etc. Denne bør altså kunne understøtte et “varslingssenter” som kan vises/integreres for brukerne i Arbeidsflate, portaler, apper, etc. Med støtte for tilgangsstyring.
Push-varslinger til mobil har noen viktige svakheter. De drukner fort i mengden, de kan disables, man må ha en app installert, de fungerer best når man skal agere med en gang, de er låst til økosystemer eid av amerikanske giganter. Sikkerhet er da også et spørsmål, og man skal/kan aldri inkludere sensitiv, personlig eller konfidensiell info i et push-varsel."

**Comment by AudunFK** [comment]
Merged into https://github.com/digdir/dialogporten-frontend/issues/1582#issue-2741990219 - as it is a duplicate
