### ISSUE TITLE
Process of going from from a user need to a prioritised feature

### ISSUE THREAD

**Issue by AudunFK** [digdir/dialogporten-frontend#86]
**Description** 
We are in the process of identifying user needs and prioritizing them for development in connection with the reimplementation of the Altinn innboks. To structure the process of going from insights to functionality. We have defined a process for identifying and documenting the user’s needs. 
 
We start by going through previously collected insights, conducting research and analyzing the findings. The processes have yielded 2 overarching users’ needs which can be further detailed in a category of 6 user needs. 
 
**The link to the list will be pulished here on monday**

**##The defined process"** 
 
1)    **Identify the core user needs.** 
This process has already been conducted and Its based on previously conducted researched combined with interviews and findings. Future user needs can be added as we continue the research phase of the project. 
 
2)    **Document “as is”** 
image connected to the user need. Show how the current solution and highlight issues
 
3)    **Best practice**
Collect best practices on how to respond to the user needs and improve the “as is” solution in the current inbox. 
 
4)    **Define hypothesis**
To test are assumptions regarding solution to the user need. The hypothesis will be collected and stored in a “hypothesis three” A three is used to visualize the different hypothesis, test, and findings we collect in the process of proving them right/wrong

- [x] #103

5)  **Design**    
Conceptualize new design or functionality corresponding with the selected user need
 
6)    **User testing** 
Testing the designed functionality to validate or disprove the hypothesis. At the current state, prior to the declarations of privacy – we will conduct Gerilja tests that won’t require us to collect and store personal information.   
 
 7)    **Prioritising** 
When finished, this process will provide a collection of documented and testet features. The project team can then easily process the list and decide what functionality is prioritized for Phase A or B - based on technical complexity and the impact on the customer experience. 

8) **Ready for development** 

 
 
```[tasklist]
### Tasks
- [ ] Define and create hypothesis overview
```

**Comment by AudunFK** [comment]
![Image](https://github.com/digdir/dialogporten-frontend/assets/15613654/24bb026c-1822-4a99-8720-f22df2eb0d46)

**Comment by indiamaydesign** [comment]
To be revisited after Q1 to check-in on process.
