### ISSUE TITLE
Som et minimum for verifisering av Dialoger opprettet må Transmissions vises som en liste

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#871]
Transmissions er blitt introdusert (avløser dialog elements), jf. schema-endringer https://npmdiff.dev/%40digdir%2Fdialogporten-schema/1.8.1-af262b1/1.8.1-3ca495f/ Se https://github.com/digdir/dialogporten/issues/860 for mer informasjon om konseptet. 

Benytter som en **interim** løsning design/komponent for aktiviteter med vedlegg. 

Enkleste veien til mål for å oppnå nettopp dette er antagelig:

1. Berike `GetDialogByIdQuery` med hensiktsmessige felter fra fra `Transmission` (id, createdAt, type, sender, content, attachments?)
2. Mappe det om slik at man får en flat struktur som gir mening for UI og hekte det på `DialogByIdDetails`
3. Kopiere section som mapper ut `activities` i `InboxItemDetail`, som rendrer en Transmission-komponent (som kan bare være en kopi / basere seg på Activity).
4. Ordne listen etter created at (det finnes ikke noe updated at, og det vil ikke oppdateres)
5. Vedlegg, tekst (title og summary fra content) og avsender gir kanskje mest mening å vise?

**Comment by LeifHelstad** [comment]
**Test**
Skatt har delt nøkler til det de mener er en mer "vanlig" melding:

312828227 / innsender
 
314099788 / oppgavegiver.
 
{
"dialogId": "01932f54-0f01-71fe-a94d-8e017089f822",
 "transmissionId": "01932f54-0f95-7edd-82f3-10e4db578ae1",
 "oppgavegiversLeveranseReferanse": "string",
"antallOppgaver": 1
}

Pålogget som 20916199776 

Meldingen fra 15.november inneholder transmisjoner opprettet av skatt.

![image](https://github.com/user-attachments/assets/7774b4e4-fa48-45eb-8e9e-407452f6bae3)

**Comment by LeifHelstad** [comment]
**Testresultater:**
Transmisjonskjeden har kun en maks bredde på 1 (en "tråd" uten mulighet for "fork").
"Hierarchy width violation found. 'DialogTransmission' with the following ids has to many referring DialogTransmission, exceeding the max allowed width of 1: [01935385-9db0-72a4-9152-dde53f489af2]."
--- Utelater TC-2.1 fra testen

Dannet dialog "01939646-3171-7762-a197-c25fb085de0e" som kan sjekkes på med bruker 08895699684.

**Comment by LeifHelstad** [comment]
**Testresultat:**
Transmissions vises i en liste i dialogen = Passed

**Observasjon:**
At noen av transmisjonene har en relatedTransmission til hverandre fremkommer ikke.
Hverken at de tre 2-erne har en realsjon eller at 1-eren ikke har noen relasjon til 2-erne.

![image](https://github.com/user-attachments/assets/f7d0a256-d9ea-4a17-94ec-bee09f3b83f9)

**Comment by LeifHelstad** [comment]
**Testresultat av utvidet test:**
En ny transmission som er related til den andre som er related til den initelle (TC-2.2.2)
"relatedTransmissionId": "01935385-9db0-72a4-9152-dde53f489f22"
"Hierarchy width violation found. 'DialogTransmission' with the following ids has to many referring DialogTransmission, exceeding the max allowed width of 1: [01935385-9db0-72a4-9152-dde53f489f22]."

En ny frittstående transmission legges til (TC-3)
Dannes og kommer "på toppen". Det kan virke som lista er sortert fallene på tid.

-> En siste test: Hvor vil en TC-2.2.1.1 innplassere seg?
- A: Øverst kun basert på fallende tid?
- B: Øverst blant de relatere 2-erne (siden den blant dem er nyeste alternativt sist i kjeden)

**Comment by LeifHelstad** [comment]
**Testresultat fra en siste test:**
Lista over Transmissions virker å være sortert globalt på dato uten hensyn til "relatedTransmissionId"

Basert på kriteriene 1, 2, 3, 4 og 5 første kommentar her (Jul 30) så er ikke related nevnt, listen skal være flat og sortert etter created. Alt dette er oppfylt. Setter "Test Passed".

![image](https://github.com/user-attachments/assets/006abb42-4a28-41b2-b0b8-becf3932948a)
