### ISSUE TITLE
Today's (as-is) user journey

### ISSUE THREAD

**Issue by LisLonning** [digdir/dialogporten-frontend#9]
## Description
Map as-is (today's) user journey. Which challenges do people face today, at what time and in which situations they are in contact with various public sector actors.

## Additional information
Add more details as need like links, architecture sketches etc.

## Tasks
Add tasks to be done as part of this issue.

## Acceptance criteria
Define the acceptance criterias that this user story should testet against (if relevant).

**Comment by sorensensig** [comment]
Similar issue have been created [here](https://github.com/digdir/dialogporten-frontend-react/issues/70). Closing this issue.
