### ISSUE TITLE
SeenBy avatar visning

### ISSUE THREAD

**Issue by alexdigdir** [digdir/dialogporten-frontend#912]
![Image](https://github.com/user-attachments/assets/f5e3a22b-fc3b-4b26-8046-b9cec302e029)

**Comment by seanes** [comment]
Dette er kanskje ikke relevant, og listen som skisseres her skal muligens representere noe annet.

**Comment by seanes** [comment]
Lukkes til fordel for ny, fremtidig oppgave, der potensielt avatarer representerer aktørerer med aktivitet på dialogen.
