### ISSUE TITLE
Bug: list of saved searches on small screens (e.g. mobile)

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#941]
<SearchFilterTags /> are colliding and creating an unreadable list. 

![Image](https://github.com/user-attachments/assets/7f441c78-939c-4734-a397-6b98c2797c22)

Should probably be aligned with task / work for saved searches in general.

Update:
https://www.figma.com/design/yZLfugRSXOsdIXsZ7W5h43/Inbox-UI-%E2%80%93-del-A?node-id=1953-23824&m=dev

**Comment by seanes** [comment]
@ingefossland Denne må adresseres, på lik linje med at lagrede favoritter ikke har et detaljert design. 
En interim-løsning kan være å flex-wrappe elementene med en fast størrelse i kolonne og på rad.

Eksempelvis:

```
    display: flex;
    flex-wrap: wrap;
    row-gap: 6px;
    column-gap: 6px;
```


![Image](https://github.com/user-attachments/assets/0f3ac8da-3c1f-4ff6-92b7-2839bdf53848)

**Comment by LeifHelstad** [comment]
Via af.tt opplever jeg ikke at feltene legger seg over hverandre så denne er nok allerede løst når Prosjekt status ble satt til Done.
Endrer derfor Repo status fra Open til Closed slik at den ikke dukker opp som Open i statistikk når den er løst.

![Image](https://github.com/user-attachments/assets/ff4fdeb9-044d-45cb-bc48-c14ac8847edb)
