### ISSUE TITLE
UI for add/remove favourite

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#958]
Users expect to be able to organize actors into favourites (like today).

**Comment by AudunFK** [comment]
Lukkes, videre status på temaet kan følges på: 

Som privatperson med tilgang til flere aktører ønsker jeg å gruppere og favorisere aktører, slik at jeg får enkel tilgang til mine favoritt-aktører.
[#1600](https://github.com/digdir/dialogporten-frontend/issues/1600)

**Comment by LeifHelstad** [comment]
## Test
Oppfatter at denne egentlig skulle vært "Close as duplicate" ikke "Close as complete" siden alt saken omhandler skal følges opp videre i https://github.com/digdir/dialogporten-frontend/issues/1600
