### ISSUE TITLE
Saved searches UI

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#978]
Detaljere ut mobilvisning av lagrede søk med flere filter.

**Comment by AudunFK** [comment]
Duplikat - dekkes videre her: Som en innbygger med lagrede søk trenger jeg muligheten til å utføre, endre og slette de lagrede søkene, slik at jeg kan enkelt kan ha kontroll over relevante gjentagende oppgaver
[#1509](https://github.com/digdir/dialogporten-frontend/issues/1509)
