### ISSUE TITLE
Seperate between confidential mail and regular mail

### ISSUE THREAD

**Issue by sorensensig** [digdir/dialogporten-frontend#99]
### Description

Service desk has forwarded information where some users struggle to see the difference between confidential mail and regular mail. Can we make changes to the inbox so that this seperation is easier for users to understand? A suggested fix is to seperate these by colours.

**Comment by AudunFK** [comment]
Added another user story that covers this issue https://github.com/digdir/dialogporten-frontend/issues/1627#issue-2755827152
